name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write  # Allow write access to the repository contents
  pages: write     # Allow write access to GitHub Pages
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify the Node.js version you want to use
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
      - name: Show Build
        run: ls -la public

      - name: Configure Git
        run: |
          git config --global user.name "oyic"
          git config --global user.email "oyic@outlook.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public  # Path to the directory to publish
          publish_branch: gh-pages  # Specify the branch to deploy to